package.json	@modelcontextprotocol/sdk	^1.25.3
package.json	bluebird	^3.7.2
package.json	child_process	^1.0.2
package.json	chokidar	^5.0.0
package.json	clipboard-copy	^4.0.1
package.json	co	^4.6.0
package.json	colors	^1.4.0
package.json	commander	^14.0.3
package.json	crypto-js	^4.2.0
package.json	dox	^1.0.0
package.json	ejs	^4.0.1
package.json	exceljs	^4.4.0
package.json	extend	^3.0.2
package.json	front-matter	^4.0.2
package.json	handlebars	^4.7.8
package.json	i	^0.3.7
package.json	immutable	^5.1.4
package.json	js-yaml	^4.1.0
package.json	linebyline	^1.3.0
package.json	lodash	^4.17.23
package.json	mkdirp	^3.0.1
package.json	mockjs	^1.1.0
package.json	mysql2	^3.11.0
package.json	random-js	^2.1.0
package.json	superagent	^10.3.0
package.json	taffydb	^2.7.3
package.json	underscore	^1.13.7
package.json	uuid	^13.0.0
package.json	zod	^4.3.6